config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "components", to: 'pages#components'
  get "swaped", to: 'pages#swaped'

  resources :items do
    resources :liked, only: [:create]
    collection do
      get :my_items
    end
    resources :offers, only: [:new] do
      collection do
        get :select_item
      end
    end
  end

  resources :offers, only: [:create, :index] do
      member do
        get :offer_confirm
        get :offer_decline
      end
      collection do
        get :my_swaps
      end
  end

  resources :liked, only: [:destroy, :index]

  resources :chatrooms, only: [:index, :show, :new] do
    resources :messages, only: :create
  end
end

app/views/shared/_banner.html.erb
  <div class="banner">
    <div class="banner1 d-flex justify-content-center align-items-center">
      <h1 class="blue">No Sweat <span class="white">/</span> <span class="green">Swap It</span></h1>
    </div>
    <div class="banner2 d-flex justify-content-center align-items-center flex-column">
      <h3 class="banner-text">Any easy simple way to exchange items you no longer want, but that are still completely useful</h3>
      <%= link_to "TRY NOW", items_path, class: "btn btn-primary swap-it-btn" %>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-sync-alt icon-b"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "<i class='fas fa-comments green'></i>".html_safe, chatrooms_path, class: "nav-link  btn btn-primary navbar-btn" %>
        </li>
        <li class="nav-item">
          <%= link_to "<i class='fas fa-heart red heart'></i>".html_safe, liked_index_path, class: "nav-link  btn btn-primary navbar-btn" %>
        </li>
        <li class="nav-item">
          <%= link_to "<i class='fas fa-sync-alt icon-b'></i>".html_safe, offers_path, class: "nav-link  btn btn-primary navbar-btn" %>
        </li>
        <li class="nav-item dropdown">
        <!-- upload avatar -->
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, stylefit: :cover, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "https://images.unsplash.com/photo-1472491235688-bdc81a63246e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60", stylefit: :cover, class: "avatar-square dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Account", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "My Items", my_items_items_path, class: "dropdown-item" %>
            <%= link_to "My Swaps", my_swaps_offers_path, class: "dropdown-item" %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>