config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "components", to: 'pages#components'
  get "swaped", to: 'pages#swaped'

  resources :items do
    resources :liked, only: [:create]
    collection do
      get :my_items
    end
    resources :offers, only: [:new] do
      collection do
        get :select_item
      end
    end
  end

  resources :offers, only: [:create, :index] do
      member do
        get :offer_confirm
        get :offer_decline
      end
      collection do
        get :my_swaps
      end
  end

  resources :liked, only: [:destroy, :index]

  resources :chatrooms, only: [:index, :show, :new] do
    resources :messages, only: :create
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :asker, :class_name => 'Item'
  belongs_to :receiver, :class_name => 'Item'
  has_one :asker_user, through: :asker, source: :user
  has_one :receiver_user, through: :receiver, source: :user
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def select_item
    skip_authorization
    @my_items = Item.all.select { |item| item.user_id == current_user.id && item.active }
    @requested_item = Item.find(params[:item_id])
  end

  def new
    skip_authorization
    @requested_item = Item.find(params[:item_id])
    @selected_item = Item.find(params[:item])
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    authorize @offer
    @offer.status = 0
    if @offer.asker != @offer.receiver && @offer.asker.user == current_user && @offer.save!
      redirect_to swaped_path
    else
      render :new
    end
  end

  def index
    offers = Offer.all
    offers = policy_scope(Offer)
    @my_offers = offers.select { |offer| offer.receiver_user == current_user && offer.status == 0 }
  end

  def offer_decline
    offer = Offer.find(params[:id])
    authorize offer
    offer.update(status: 2)
    flash[:notice] = 'Swap rejected!'
    redirect_to offers_path
  end

  def offer_confirm
    @offer = Offer.find(params[:id])
    authorize @offer
    if @offer.asker.active == true && @offer.receiver.active == true
      # make sure to disable item
      item_1 = Item.find(@offer.asker.id)
      item_1.update(active: false)
      item_2 = Item.find(@offer.receiver.id)
      item_2.update(active: false)
      # auto decline all offers which involve either asker or receiver of confirmed offer
      offers = Offer.all.select { |offer| (offer.asker.id == @offer.asker.id || offer.asker.id == @offer.receiver.id || offer.receiver.id == @offer.asker.id || offer.receiver.id == @offer.receiver.id) && offer.id != @offer.id }
      offers.each { |offer| offer.update(status: 2) }
      @offer.update(status: 1)
      flash[:notice] = 'Swap accepted!'
    else
      flash[:notice] = 'The item has already been swapped. Sorry!'
    end
    redirect_to offers_path
  end

  def my_swaps
    @offers = Offer.all
    authorize @offers
    @my_swaps = @offers.select { |offer| (offer.receiver_user == current_user || offer.asker_user == current_user) && offer.status == 1 }
  end

  protected

  def offer_params
    params.require(:offer).permit(:asker_id, :receiver_id)
  end
end

app/views/offers/index.html.erb
<% if @my_offers.empty? %>
  <div class="chat-container d-flex flex-column justify-content-center align-items-center mt-5">
    <h2 class="center">No offers to swap yet!</h2>
    <%= link_to "Look at items to swap!", items_path, class: "btn btn-primary save-btn my-1" %>
  </div>
<% else %>
  <div class="chat-container">
    <% @my_offers.each do |offer| %>
      <div class="my-1">
        <div class="card-product">
          <img class="product-img" src="<%= cl_image_path offer.asker.photos[0].key %>">
          <div class="card-product-infos">
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <h2><%= link_to offer.asker.title, item_path(offer.asker), class: "white" %></h2>
                <p><%= offer.asker.description %></p>
                <% offer.asker.price.to_i.times do  %>
                  <span class="euro"><i class="fas fa-euro-sign"></i></span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-center align-items-center">
    <%= link_to "<i class='fas fa-sync-alt icon-b navbar-brand'></i> Swap it!".html_safe, class: "btn btn-primary swap-it-btn m-3" %>
    <%= link_to "<i class='fas fa-times red'></i> Reject Swap".html_safe, class: "btn btn-primary save-btn m-3" %>
  </div>
  <div class="chat-container">
    <% @my_offers.each do |offer| %>
      <div class="my-1">
        <div class="card-product">
          <img class="product-img" src="<%= cl_image_path offer.receiver.photos[0].key %>">
          <div class="card-product-infos">
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <h2><%= link_to offer.receiver.title, item_path(offer.receiver), class: "white" %></h2>
                <p><%= offer.receiver.description %></p>
                <% offer.receiver.price.to_i.times do  %>
                  <span class="euro"><i class="fas fa-euro-sign"></i></span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/offers/my_swaps.html.erb
<% if @my_swaps.empty? %>
  <div class="chat-container d-flex flex-column justify-content-center align-items-center mt-5">
    <h2 class="center">No swaps yet!</h2>
    <%= link_to "Look at items to swap!", items_path, class: "btn btn-primary save-btn my-1" %>
  </div>
<% else %>
  <% @my_swaps.each do |offer| %>
  <div class="chat-container">
      <div class="my-1">
        <div class="card-product">
          <img class="product-img" src="<%= cl_image_path offer.asker.photos[0].key %>">
          <div class="card-product-infos">
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <h2><%= link_to offer.asker.title, item_path(offer.asker), class: "white" %></h2>
                <p><%= offer.asker.description %></p>
                <% offer.asker.price.to_i.times do  %>
                  <span class="euro"><i class="fas fa-euro-sign"></i></span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to "<i class='fas fa-sync-alt icon-b navbar-brand'></i> Swapped!".html_safe, "#", class: "btn btn-primary swap-it-btn m-3" %>
    </div>
    <div class="chat-container">
        <div class="my-1">
          <div class="card-product">
            <img class="product-img" src="<%= cl_image_path offer.receiver.photos[0].key %>">
            <div class="card-product-infos">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h2><%= link_to offer.receiver.title, item_path(offer.receiver), class: "white" %></h2>
                  <p><%= offer.receiver.description %></p>
                  <% offer.receiver.price.to_i.times do  %>
                    <span class="euro"><i class="fas fa-euro-sign"></i></span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  <% end %>
<% end %>

app/views/offers/new.html.erb
<div class="chat-container">
  <h2>Item Selected to Swap for:</h2>
  <div class="my-1">
    <div class="card-product">
      <img class="product-img" src="<%= cl_image_path @requested_item.photos[0].key %>">
      <div class="card-product-infos">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <h2><%= link_to @requested_item.title, item_path(@requested_item), class: "white" %></h2>
            <p><%= @requested_item.description %></p>
            <% @requested_item.price.to_i.times do  %>
              <span class="euro"><i class="fas fa-euro-sign"></i></span>
            <% end %>
          </div>
          <div class= "d-flex justify-content-center align-items-center avatar-box">
            <div class="pr-2">
             <%= cl_image_tag @requested_item.user.photo.key, class: "avatar-bordered", alt: "avatar-bordered" %>
            </div>
            <div class = "avatar-info">
              <p style="font-size: 0.80rem;"><%= @requested_item.user.username %></p>
              <p class="font-weight-light"><%= @requested_item.user.location %></p>
              <p class="font-weight-light"><i class="fas fa-map-marker-alt blue"></i><%= @requested_item.user.distance_to(current_user.geocode).nil? ?  " Your Item" : " #{@requested_item.user.distance_to(current_user.geocode).round(1)} km" %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="chat-container mt-3">
  <h2>Your Item that you wish to Swap:</h2>
    <div class="my-1">
      <div class="card-product">
        <img class="product-img" src="<%= cl_image_path @selected_item.photos[0].key %>">
        <div class="card-product-infos">
          <div class="d-flex justify-content-between align-items-center">
            <div>
          <h2><%= link_to @selected_item.title, item_path(@selected_item), class: "white" %></h2>
              <p><%= @selected_item.description %></p>
              <% @selected_item.price.to_i.times do  %>
                <span class="euro"><i class="fas fa-euro-sign"></i></span>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

<div class="chat-container mt-3 flex-column d-flex justify-content-center align-items-center">
  <div class="container">
    <%= simple_form_for @offer, html: { class: "login-form"} do |f|%>
      <%= f.input :asker_id, :as => :hidden, input_html: { value: @selected_item.id } %>
      <%= f.input :receiver_id, :as => :hidden, input_html: { value: @requested_item.id } %>
      <%= f.submit "confirm", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/offers/select_item.html.erb
<div class="chat-container">
  <h2>Item Selected to Swap for:</h2>
  <div class="my-1">
    <div class="card-product">
      <img class="product-img" src="<%= cl_image_path @requested_item.photos[0].key %>">
      <div class="card-product-infos">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <h2><%= link_to @requested_item.title, item_path(@requested_item), class: "white" %></h2>
            <p><%= @requested_item.description %></p>
            <% @requested_item.price.to_i.times do  %>
              <span class="euro"><i class="fas fa-euro-sign"></i></span>
            <% end %>
          </div>
          <div class= "d-flex justify-content-center align-items-center avatar-box">
            <div class="pr-2">
             <%= cl_image_tag @requested_item.user.photo.key, class: "avatar-bordered", alt: "avatar-bordered" %>
            </div>
            <div class = "avatar-info">
              <p style="font-size: 0.80rem;"><%= @requested_item.user.username %></p>
              <p class="font-weight-light"><%= @requested_item.user.location %></p>
              <p class="font-weight-light"><i class="fas fa-map-marker-alt blue"></i><%= @requested_item.user.distance_to(current_user.geocode).nil? ?  " Your Item" : " #{@requested_item.user.distance_to(current_user.geocode).round(1)} km" %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% if @my_items.empty? %>
  <div class="chat-container d-flex flex-column justify-content-center align-items-center mt-5">
  <h2 class="center">No Items yet Added</h2>
  <%= link_to "Add an Item!", new_item_path, class: "btn btn-primary save-btn my-1" %>
  </div>
<% else %>
  <div class="chat-container mt-3">
    <h2>Your Items to Swap:</h2>
    <% @my_items.each do |item| %>
        <div class="my-1">
          <div class="card-product">
            <img class="product-img" src="<%= cl_image_path item.photos[0].key %>">
            <div class="card-product-infos">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h2><%= link_to item.title, new_item_offer_path(:item => item.id), class: "white" %></h2>
                  <p><%= item.description %></p>
                  <% item.price.to_i.times do  %>
                    <span class="euro"><i class="fas fa-euro-sign"></i></span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
<% end %>