config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "components", to: 'pages#components'
  get "swaped", to: 'pages#swaped'

  resources :items do
    resources :liked, only: [:create]
    collection do
      get :my_items
    end
    resources :offers, only: [:new] do
      collection do
        get :select_item
      end
    end
  end

  resources :offers, only: [:create, :index] do
      member do
        get :offer_confirm
        get :offer_decline
      end
      collection do
        get :my_swaps
      end
  end

  resources :liked, only: [:destroy, :index]

  resources :chatrooms, only: [:index, :show, :new] do
    resources :messages, only: :create
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_and_belongs_to_many :tags
  has_many :chatrooms, dependent: :destroy
  has_many :items, through: :liked
  has_many :offers_as_asker, :class_name => 'Offer', :foreign_key => 'asker_id'
  has_many :offers_as_receiver, :class_name => 'Offer', :foreign_key => 'receiver_id'

  validates :title, :price, :photos, :description, presence: true
  validates :price, inclusion: { in: 0..3 }
  validates :title, uniqueness: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = policy_scope(Item)
#@items = Item.all.select { |item| item.active }
    if params[:tags].present?
      @selected_tags = params[:tags].split(",")
      @items = Item.joins(:tags).where(tags: { name: @selected_tags }).group('items.id').having("count('tags.name') = ?", @selected_tags.size)
      @items = @items.select { |item| item.active }
    else
      @selected_tags = []
    end

    @tags = Tag.all

    users = []
    @items.each do |item|
      users.append(item.user)
    end

    users = users.uniq
    users.each do |user|
      coords = user.geocode
      user.longitude = coords[1]
      user.latitude = coords[0]
    end

    @markers = users.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { user: user })
      }
    end
  end

  def show
    @item = Item.find(params[:id])
    @item_liked = Liked.find_by(item_id: @item.id, user_id: current_user)
    authorize @item
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    @item.active = true
    authorize @item
    if @item.save!
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item
  end

  def update
    authorize @item
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.active = false
    authorize @item
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to items_path, notice: 'The item was successfully destroyed.'
  end

  def my_items
    @my_items = Item.all.select { |item| item.user == current_user && item.active }
    authorize @my_items
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :price, :description, tag_ids: [], photos: [])
  end
end

app/views/items/_form.html.erb
<div class="container">
  <%= simple_form_for @item, html: { class: "login-form"} do |f|%>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.association :tags,
                  as: :check_boxes,
                  input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item',
                  collection: Tag.all %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/items/_info_window.html.erb
<p class="mb-0 dark-blue"><%= user.username %></p>
<% user.items.each do |item| %>
  <% if item.active %>
  <div>
    <img class='product-img' src='<%= cl_image_path item.photos[0].key%>'>
    <%= link_to item.title, item_path(item) %>
  </div>
  <% end %>
<% end %>

app/views/items/edit.html.erb
<div class="container">
  <h1 class="title text-center">Edit Item</h1>
  <%=  render 'form' %>
</div>

app/views/items/index.html.erb
<div class="container">
  <h4 class="text-center">items | map</h4>
  <div class="row">
    <div class="col-4">
      <div class="filter d-flex flex-column justify-content-start align-items-center">
        <h3 class="mt-4">Tags</h3>
        <div class="tag-container">
          <% @tags.each do |tag| %>
            <% tag_link = Tag.formatLink(@selected_tags.dup, tag.name) %>
            <% if @selected_tags.include? tag.name %>
              <%= link_to tag.name, items_path(:tags => tag_link), class: "btn btn-primary tag mx-1 mb-1 tag-selected" %>
            <% else %>
              <%= link_to tag.name, items_path(:tags => tag_link), class: "btn btn-primary tag mx-1 mb-1" %>
            <% end %>
          <% end %>
        </div>
        <h3 class="mt-4">Categories</h3>
      </div>
    </div>
    <div class="col-8">
      <% @items.each do |item| %>
        <div class="my-1">
          <div class="card-product">
            <img class="product-img" src="<%= cl_image_path item.photos[0].key %>">
            <div class="card-product-infos">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h2><%= link_to item.title, item_path(item), class: "white" %></h2>
                  <p><%= item.description %></p>
                  <% item.price.to_i.times do  %>
                    <span class="euro"><i class="fas fa-euro-sign"></i></span>
                  <% end %>
                </div>
                <div class= "d-flex justify-content-center align-items-center avatar-box">
                  <div class="pr-2">
                   <%= cl_image_tag item.user.photo.key, class: "avatar-bordered", alt: "avatar-bordered" %>
                  </div>
                  <div class = "avatar-info">
                    <p style="font-size: 0.80rem;"><%= item.user.username %></p>
                    <p class="font-weight-light"><%= item.user.location %></p>
                    <p class="font-weight-light"><i class="fas fa-map-marker-alt blue"></i><%= item.user.distance_to(current_user.geocode).nil? ?  " near you" : " #{item.user.distance_to(current_user.geocode).round(1)} km" %></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="m-5" id="map"
    style="width: 90%; height:500px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/items/my_items.html.erb
<% if @my_items.empty? %>
  <div class="chat-container d-flex flex-column justify-content-center align-items-center mt-5">
    <h2 class="center">No Items yet listed</h2>
    <%= link_to "Add an Item!", new_item_path, class: "btn btn-primary save-btn my-1" %>
  </div>
<% else %>
  <div class="chat-container">
    <%= link_to "Add an Item!", new_item_path, class: "btn btn-primary save-btn my-2 mx-auto d-block" %>
    <% @my_items.each do |item| %>
        <div class="my-1">
          <div class="card-product">
            <img class="product-img" src="<%= cl_image_path item.photos[0].key %>">
            <div class="card-product-infos">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h2><%= link_to item.title, item_path(item), class: "white" %></h2>
                  <p><%= item.description %></p>
                  <% item.price.to_i.times do  %>
                    <span class="euro"><i class="fas fa-euro-sign"></i></span>
                  <% end %>
                </div>
                <div class= "d-flex justify-content-center align-items-center flex-column">
                    <%= link_to "<i class='fas fa-pencil-alt'></i>".html_safe, edit_item_path(item), class: "btn btn-primary navbar-btn mb-2" %>
                    <%= link_to "<i class='far fa-trash-alt'></i>".html_safe, item_path(item), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn-primary btn navbar-btn" %>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/items/new.html.erb
<div class="container">
  <h1 class="title text-center">Add an Item</h1>
  <%=  render 'form' %>
</div>

app/views/items/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-7">
        <div id="<%= 'carousel' + @item.id.to_s %>" class="carousel slide" data-ride="carousel" data-interval="10000">
          <ol class="carousel-indicators">
            <% @item.photos.each_with_index do |photo, idx|  %>
              <li data-target="#<%= 'carousel' + @item.id.to_s %>" data-slide-to="0" class="active"></li>
            <% end %>
          </ol>
            <div class="carousel-inner">
              <% @item.photos.each_with_index do |photo, idx|  %>
                <div class="carousel-item <%= 'active' if idx == 0  %>">
                  <div>
                    <img src="<%= cl_image_path @item.photos[idx].key %>" alt="item images">
                  </div>
                </div>
              <% end %>
            <a class="carousel-control-prev" href="#<%= 'carousel' + @item.id.to_s %>" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#<%= 'carousel' + @item.id.to_s %>" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
    </div>
    <div class="col-5">
      <div class="swap-action d-flex flex-column justify-content-center align-items-center mb-3">
        <h2 class="mb-1"><%= @item.title %></h2>
        <p class="px-3"><%= @item.description %></p>
        <div class="d-flex justify-content-around align-items-center">
          <% @item.tags.each do |tag| %>
            <button class="btn btn-primary tag mx-1 mb-1"><%= tag.name %></button>
          <% end %>
        </div>
        <div class="d-flex justify-content-between align-items-center mb-4">
          <% @item.price.to_i.times do  %>
            <span class="euro-lg"><i class="fas fa-euro-sign"></i></span>
          <% end %>
        </div>
        <%= link_to "<i class='fas fa-sync-alt'></i> Swap It".html_safe, select_item_item_offers_path(@item), class: "btn btn-primary swap-it-btn my-1" %>
        <% if @item_liked.nil? %>
          <%= link_to "<i class='fas fa-heart red'></i> Save It".html_safe, item_liked_index_path(@item), method: :post, class: "btn btn-primary save-btn my-1" %>
        <% else %>
            <%= link_to "Remove it", liked_path(@item_liked), method: :delete, class: "btn btn-primary save-btn my-1" %>
        <% end %>
        <%= link_to "<i class='fas fa-comments green'></i> Send a Message".html_safe, new_chatroom_path(item: @item, user: current_user), class: "btn btn-primary message-btn my-1" %>

      </div>
      <div class="owners-info d-flex justify-content-around align-items-center">
        <div class="d-flex justify-content-center align-items-center">
          <div class="pr-2">
           <%= cl_image_tag @item.user.photo.key, class: "avatar-bordered-lg", alt: "avatar-bordered" %>
          </div>
          <div class = "avatar-info">
            <p style="font-size: 0.80rem; margin-bottom: 0;"><%= @item.user.username %></p>
            <p class="font-weight-light mb-0"><%= @item.user.location %></p>
            <p class="font-weight-light mb-0" style="font-size: 0.80rem"><i class="fas fa-map-marker-alt blue"></i><%= @item.user.distance_to(current_user.geocode).nil? ?  " Your Item" : " #{@item.user.distance_to(current_user.geocode).round(1)} km" %></p>
          </div>
        </div>
        <div>
          <i class="far fa-smile smile-icon"></i>
        </div>
        <div>
          <p class="mb-0">Active Since</p>
          <p class="mb-0"><%= @item.user.created_at.strftime("%B %d") %> 2020</p>
        </div>

      </div>
    </div>
  </div>
</div>